### PR TITLE
Fixed self reply check (and removed comment)

### PR DESCRIPTION
**Pull request by soilheart**
The self reply check was broken.

I also removed the reply as I feel like a report is quite enough. (In the case I found, it was a false positive where the user had replied to himself asking mechkbot why he didn't get confirmed).

### CODE REVIEW

**Comment by Chankster** [comment]
I mainly had the reply so that bot actions would be clear to users and it wouldn't look like the bot is ignoring stuff.  

@thelectronicnub if you don't mind, give me a chance to review before pulling the trigger

**Comment by soilheart** [comment]
My thought is that a self-reply should warrant mod action anyway.

**Comment by nathaniel-ortiz** [comment]
maybe make the reply option able to be toggled on and off, ie leaving the  `equal =` field blank

**Comment by Chankster** [comment]
True, but usually the bot reports on confirmed trade threads end up looking like a giant mess of reports and it would be easy (for me) to miss.  

I agree with just checking for a blank reply message.  The idea could be expanded to all the bot responses.  That way you wouldn't need a specific 'reply=yes' (ie heatware.py) to turn on and off each reply type.

**Pull request merged**
